# NUMPY KÜTÜPHANESİ

NumPy yani Numerical Python, çok boyutlu dizilerle ve matrislerle çalışmamızı sağlayan ve matematiksel işlemler yapabildiğimiz bir kütüphanedir. Numpy ile Python'un mevcut dizilerine oranla daha verimli ve daha az kodla matematiksel işlemler yapabiliriz.

Python’da dizilerin amacına hizmet eden listelerimiz var, ancak işlenmesi yavaştır. NumPy, geleneksel Python listelerinden 50 kata kadar daha hızlı bir dizi nesnesi sağlamayı amaçlamaktadır. 

NumPy bir Python kütüphanesidir ve kısmen Python’da yazılmıştır, ancak hızlı hesaplama gerektiren parçaların çoğu C veya C ++ ile yazılmıştır.

Numpy, Python’daki dizilerden (list, tuple) farklı olarak her bir elemanının aynı türde olduğu sayısal dizileri içermektedir.

NumPy’deki dizi nesnesi (array) ndarray olarak adlandırılır ve ndarray, çalışmayı çok kolaylaştıran birçok destekleyici işlev sağlar. NumPy dizileri ile standart Python dizileri arasında bazı farklar vardır. 

Standart Python listeleri dinamik olarak büyüyebilen diziler iken, NumPy dizileri oluşturulurken sabit bir boyuta sahiptir. Bir ndarray boyutunu değiştirdiğinizde yeni bir dizi oluşturulur ve orjinali silinir.

Numpy ile çok boyutlu dizi işlemleri döngü kullanmadan hızlı bir şekilde yapılabilir. Daha az bellek gerektirir, hızlı ve kullanışlıdır.

NumPy, çok çeşitli donanım ve bilgi işlem platformlarını destekler ve dağıtılmış, GPU ve seyrek dizi kitaplıklarıyla iyi çalışır.

In [1]:
import numpy as np

In [3]:
np.__version__   # numpy'ın yüklü olan versiyonunu elde ederiz.

'1.21.5'

In [37]:
data = np.random.randn(3,2)  # 3 satır 2 kolon
data

array([[ 0.4150363 ,  2.18458807],
       [-0.74433735,  0.73148001],
       [-0.23858096,  1.22440711]])

In [38]:
data*10

array([[ 4.15036303, 21.84588065],
       [-7.44337355,  7.31480007],
       [-2.38580956, 12.24407111]])

In [39]:
data + data

array([[ 0.83007261,  4.36917613],
       [-1.48867471,  1.46296001],
       [-0.47716191,  2.44881422]])

In [40]:
1 / data

array([[ 2.40942778,  0.4577522 ],
       [-1.34347684,  1.36709136],
       [-4.19144939,  0.81672182]])

In [7]:
data.shape

(3, 2)

In [8]:
data.dtype

dtype('float64')

NumPy, dizilerle çalışmak için kullanılır. NumPy’deki dizi nesnesine ndarray denir. array() işlevini kullanarak bir NumPy ndarray nesnesi oluşturabiliriz.

In [17]:
a = np.array(23)
a

array(23)

In [18]:
b = np.array([3,6,5,0,1,9])
b

array([3, 6, 5, 0, 1, 9])

In [19]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
print("",a.ndim, "\n", b.ndim, "\n", c.ndim, "\n", d.ndim)

# oluşturduğumuz dizi boyutlarını gözlemleyelim.

 0 
 1 
 2 
 2


In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.arange(10)  # Bir dizi üretir.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* Numpy sayısal hesaplamalar için kullanıldığı için özel olarak bir tip belirtilmediği sürece varsayılan olarak **float64** tipinde veriler üretir. Veri tipini belirtmek için **dtype** özelliğini kullanıyoruz.

In [31]:
dizi = np.array([1,2,3], dtype=int)
dizi

array([1, 2, 3])

In [32]:
dizi.dtype

dtype('int32')

* Dizinin veri tipini değiştirmek için **astype()** fonksiyonu kullanılır.

In [34]:
dizi = dizi.astype(np.float64)
dizi

array([1., 2., 3.])

In [35]:
dizi.dtype

dtype('float64')

In [41]:
arr = np.array([2,1,4,3,5,6,8,9,7])
arr

array([2, 1, 4, 3, 5, 6, 8, 9, 7])

In [42]:
arr[4]

5

In [43]:
arr[2:5]

array([4, 3, 5])

In [45]:
arr[:4] = 0
arr

array([0, 0, 0, 0, 5, 6, 8, 9, 7])

In [47]:
arr2 = np.array([[2,3,4],[1,2,3],[4,3,5]])
arr2

array([[2, 3, 4],
       [1, 2, 3],
       [4, 3, 5]])

In [48]:
arr2[0]

array([2, 3, 4])

In [50]:
arr2[0][2]

4

In [51]:
arr2[0:2]

array([[2, 3, 4],
       [1, 2, 3]])

In [56]:
arr2[0,:2]  # 1.bileşenin (1. satır) 2. index e kadar ki değerlerini çek

array([2, 3])

In [57]:
arr2[:2,:1] # yatayda 0. ve 1. satır, dikeyde 0. kolon

array([[2],
       [1]])

In [58]:
isimler = np.array(["Ali","Veli","Ayşe","Ali"])
isimler

array(['Ali', 'Veli', 'Ayşe', 'Ali'], dtype='<U4')

In [59]:
veri = np.random.randn(4,3)
veri

array([[ 0.06445832, -2.9707153 , -0.82911706],
       [-0.16107443, -0.50543677, -0.72229288],
       [-1.09322602,  1.05285038, -1.56668385],
       [-0.55025872, -1.39465633,  0.10293488]])

In [60]:
# isimlerin verideki satırlara karşılık geldiğini farzedelim. Yani isimleri index gibi kullanalım.
veri[isimler=="Ali"]  #Ali isimler dizisinde 0. ve 3. indexe karşılık geliyor. Verinin 0. ve 3. indexi

array([[ 0.06445832, -2.9707153 , -0.82911706],
       [-0.55025872, -1.39465633,  0.10293488]])

In [61]:
veri[isimler=="Ali", 1:]  # kolon bazında 1. indexden sonrakileri alır

array([[-2.9707153 , -0.82911706],
       [-1.39465633,  0.10293488]])

In [62]:
veri[~(isimler=="Ali")]  # "~" işareti ile Ali ismine karşılık gelmeyen elemanları verir.

# ~ ters işlemler için kullanılır.

array([[-0.16107443, -0.50543677, -0.72229288],
       [-1.09322602,  1.05285038, -1.56668385]])

In [63]:
sec = (isimler == "Ali") | (isimler == "Veli")
veri[sec]

array([[ 0.06445832, -2.9707153 , -0.82911706],
       [-0.16107443, -0.50543677, -0.72229288],
       [-0.55025872, -1.39465633,  0.10293488]])

In [65]:
veri[veri<0] = 0  # veri içerisinde 0 dan küçük elemanlar yerine 0 değerini atar.
veri

array([[0.06445832, 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 1.05285038, 0.        ],
       [0.        , 0.        , 0.10293488]])

In [66]:
dizi = np.arange(12).reshape(3,4) 
dizi

# Önce 12 elemanlı bir dizi oluşturuyor sonra da bu diziyi 3 satır 4 sütundan oluşan
# çok boyutlu bir diziye dönüştüüryoruz.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
dizi.T  # dizinin transpozunu verir. Transpoz: Satırlar ve sütunların yer değiştirme halidir.

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [69]:
# dizilerin matris çarpımı için dot() metodu kullanılır.

np.dot(dizi.T, dizi)  # diziyi dizinin transpozu ile çarpar

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

In [70]:
dizi.mean()

5.5

In [71]:
dizi.sum()

66

In [74]:
dizi.mean(axis = 1)  # satırların ortalamasını verir.

array([1.5, 5.5, 9.5])

In [75]:
dizi.mean(axis = 0) # sütunların ortalamasını verir.

array([4., 5., 6., 7.])

In [76]:
dizi.sort()  # dizi elemanları sıralanır.
dizi

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
say = np.array([1,1,1,2,3])
np.unique(say)  # tekrar eden elemanlardan sadece 1 ini alır.

array([1, 2, 3])

In [78]:
dizi = np.array(10)
np.save("bir_dizi", dizi)  # bir_dizi isminde çalışma dizinine kaydedilir.
np.load("bir_dizi.npy") # kaydettiğimiz dizi ekrana yazılır.

array(10)