# NUMPY KÜTÜPHANESİ

NumPy yani Numerical Python, çok boyutlu dizilerle çalışmamızı sağlayan ve matematiksel işlemler yapabildiğimiz bir Python kütüphanedir. NumPy kısmen Python’da yazılmıştır ancak hızlı hesaplama gerektiren parçaların çoğu C veya C ++ ile yazılmıştır. NumPy kütüphanesi Python listelerinden 50 kat daha hızlıdır.


Python listelerinden farklı olarak Numpy da dizi içerisindeki tüm elemanlar aynı veri tipinden oluşmaktadır. Python listeleri dinamik olarak büyüyebilen diziler iken, NumPy dizileri oluşturulurken sabit bir boyuta sahiptir. NumPy’deki dizi nesnesi (array) ndarray olarak adlandırılır. Bir ndarray boyutunu değiştirdiğinizde yeni bir dizi oluşturulur ve orjinali silinir. Numpy ile çok boyutlu dizi işlemleri döngü kullanmadan hızlı bir şekilde yapılabilir. Daha az bellek gerektirir, hızlı ve kullanışlıdır.

In [1]:
import numpy as np  # kütüphaneyi içe aktarıyoruz.

In [2]:
np.__version__   # numpy'ın yüklü olan versiyonunu elde ederiz.

'1.24.3'

In [3]:
data = np.random.randn(3,2)  # 3 satır 2 kolon dan oluşan random veriler üretiyoruz.
data

array([[-0.01224233,  0.99889644],
       [ 0.11437112, -0.57236011],
       [ 0.98412207,  0.17986616]])

In [4]:
data*10  # Her bir veri 10 ile çarpılır.Görüldüğü üzere döngü kullanmadan işlemi hızlı bir şekilde gerçekleştirebiliyoruz.

array([[-0.12242325,  9.98896441],
       [ 1.14371117, -5.72360113],
       [ 9.84122072,  1.79866157]])

In [5]:
data + data

array([[-0.02448465,  1.99779288],
       [ 0.22874223, -1.14472023],
       [ 1.96824414,  0.35973231]])

In [6]:
1 / data

array([[-81.68382901,   1.00110478],
       [  8.7434662 ,  -1.7471518 ],
       [  1.0161341 ,   5.55968959]])

In [7]:
data.shape

(3, 2)

In [8]:
data.dtype

dtype('float64')

NumPy, dizilerle çalışmak için kullanılır. NumPy’deki dizi nesnesine ndarray denir. array() işlevini kullanarak bir NumPy ndarray nesnesi oluşturabiliriz.

In [9]:
a = np.array(23)
a

array(23)

In [10]:
b = np.array([3,6,5,0,1,9])
b

array([3, 6, 5, 0, 1, 9])

In [11]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print("",a.ndim, "\n", b.ndim, "\n", c.ndim, "\n", d.ndim)

# oluşturduğumuz dizi boyutlarını gözlemleyelim.

 0 
 1 
 2 
 2


In [14]:
np.zeros(5)  # sıfırlardan oluşan 5 elemanlı bir dizi oluşturur.

array([0., 0., 0., 0., 0.])

In [15]:
np.ones(7)  

array([1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.arange(10)  # Bir dizi üretir.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* Numpy sayısal hesaplamalar için kullanıldığı için özel olarak bir tip belirtilmediği sürece varsayılan olarak **float64** tipinde veriler üretir. Veri tipini belirtmek için **dtype** özelliğini kullanıyoruz.

In [17]:
dizi = np.array([1,2,3], dtype=int)
dizi

array([1, 2, 3])

In [18]:
dizi.dtype

dtype('int32')

* Dizinin veri tipini değiştirmek için **astype()** fonksiyonu kullanılır.

In [19]:
dizi = dizi.astype(np.float64)
dizi

array([1., 2., 3.])

In [20]:
dizi.dtype

dtype('float64')

In [21]:
arr = np.array([2,1,4,3,5,6,8,9,7])
arr

array([2, 1, 4, 3, 5, 6, 8, 9, 7])

In [22]:
arr[4]

5

In [23]:
arr[2:5]

array([4, 3, 5])

In [24]:
arr[:4] = 0
arr

array([0, 0, 0, 0, 5, 6, 8, 9, 7])

In [25]:
arr2 = np.array([[2,3,4],[1,2,3],[4,3,5]])
arr2

array([[2, 3, 4],
       [1, 2, 3],
       [4, 3, 5]])

In [26]:
arr2[0]  # 0. satır

array([2, 3, 4])

In [27]:
arr2[0][2]  # 0. satırın 2. kolonundaki değer

4

In [28]:
arr2[0:2] 

array([[2, 3, 4],
       [1, 2, 3]])

In [29]:
arr2[0,:2]  # 1.bileşenin (1. satır) 2. index e kadar ki değerlerini çek

array([2, 3])

In [30]:
arr2[:2,:1] # yatayda 0. ve 1. satır, dikeyde 0. kolon

array([[2],
       [1]])

In [31]:
isimler = np.array(["Ali","Veli","Ayşe","Ali"])
isimler

array(['Ali', 'Veli', 'Ayşe', 'Ali'], dtype='<U4')

In [32]:
veri = np.random.randn(4,3)
veri

array([[-0.55158036,  2.23054949,  0.81951197],
       [ 0.95865405,  1.21689553, -1.7943096 ],
       [ 0.72197219, -0.87158091,  0.22764846],
       [-0.31371009,  0.50523329, -0.21608415]])

In [33]:
# isimlerin verideki satırlara karşılık geldiğini farzedelim. Yani isimleri index gibi kullanalım.
veri[isimler=="Ali"]  # Ali isimler dizisinde 0. ve 3. indexe karşılık geliyor. Verinin 0. ve 3. indexi

array([[-0.55158036,  2.23054949,  0.81951197],
       [-0.31371009,  0.50523329, -0.21608415]])

In [34]:
veri[isimler=="Ali", 1:]  # kolon bazında 1. indexden sonrakileri alır

array([[ 2.23054949,  0.81951197],
       [ 0.50523329, -0.21608415]])

In [35]:
veri[~(isimler=="Ali")]  # "~" işareti ile Ali ismine karşılık gelmeyen elemanları verir.

# ~ ters işlemler için kullanılır.

array([[ 0.95865405,  1.21689553, -1.7943096 ],
       [ 0.72197219, -0.87158091,  0.22764846]])

In [36]:
sec = (isimler == "Ali") | (isimler == "Veli")
veri[sec]

array([[-0.55158036,  2.23054949,  0.81951197],
       [ 0.95865405,  1.21689553, -1.7943096 ],
       [-0.31371009,  0.50523329, -0.21608415]])

In [37]:
veri[veri<0] = 0  # veri içerisinde 0 dan küçük elemanlar yerine 0 değerini atar.
veri

array([[0.        , 2.23054949, 0.81951197],
       [0.95865405, 1.21689553, 0.        ],
       [0.72197219, 0.        , 0.22764846],
       [0.        , 0.50523329, 0.        ]])

In [38]:
dizi = np.arange(12).reshape(3,4) 
dizi

# Önce 12 elemanlı bir dizi oluşturuyor sonra da bu diziyi 3 satır 4 sütundan oluşan çok boyutlu bir diziye dönüştürüyoruz.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
dizi.T  # dizinin transpozunu verir. Transpoz: Satırlar ve sütunların yer değiştirme halidir.

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [40]:
# dizilerin matris çarpımı için dot() metodu kullanılır.

np.dot(dizi.T, dizi)  # diziyi dizinin transpozu ile çarpar

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

In [41]:
dizi.mean()

5.5

In [42]:
dizi.sum()

66

In [43]:
dizi.mean(axis = 1)  # satırların ortalamasını verir.

array([1.5, 5.5, 9.5])

In [44]:
dizi.mean(axis = 0) # sütunların ortalamasını verir.

array([4., 5., 6., 7.])

In [45]:
dizi.sort()  # dizi elemanları sıralanır.
dizi

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
say = np.array([1,1,1,2,3])
np.unique(say)  # tekrar eden elemanlardan sadece 1 ini alır.

array([1, 2, 3])

In [47]:
dizi = np.arange(10)
np.save("bir_dizi", dizi)  # bir_dizi isminde çalışma dizinine kaydedilir.
np.load("bir_dizi.npy") # kaydettiğimiz dizi ekrana yazılır.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr) 
print(x) 

# Kopya (Copy), orijinal dizide yapılan değişikliklerden etkilenmemektedir.

[42  2  3  4  5]
[1 2 3 4 5]


In [49]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)  
print(x) 

# Görünüm (View), orijinal dizide yapılan değişikliklerden ETKİLENMELİDİR.

[42  2  3  4  5]
[42  2  3  4  5]


* Her NumPy dizisi, dizinin kendi verilerine sahip olması durumunda None döndüren base özelliğine sahiptir. Diğer bir deyişle, base nitelik orijinal nesneye atıfta bulunur.

In [50]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base) 
print(y.base)

# Özetle Kopya None değerini döndürür. Görünüm, orijinal diziyi döndürür.

None
[1 2 3 4 5]


* 1,2,3,4 değerlerine sahip bir vektörü ndmin kullanarak 5 boyutlu bir dizi şeklinde oluşturan ve son boyutun 4 değerine sahip olduğunu doğrulayan örnek bir kod yazalım:

In [51]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape: ', arr.shape)

[[[[[1 2 3 4]]]]]
shape:  (1, 1, 1, 1, 4)


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

# 2 tane 3x2 boyutunda dizi oluştur diyoruz.

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [53]:
# Şekillendirilen dizinin bir kopya mı yoksa bir görünüm mü olduğunu kontrol edebiliriz:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base) 

# orijinal diziyi döndürür, bu nedenle bir (view) görünümdür.

[1 2 3 4 5 6 7 8]


* Düzleştirme dizisi, çok boyutlu bir diziyi 1 boyutlu bir diziye dönüştürmek anlamına gelir. Bunu yapmak için reshape(-1) kullanabiliriz.

In [54]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


Yineleme (Iterating), öğeleri tek tek gözden geçirmek anlamına gelir. Numpy’deki çok boyutlu dizilerle uğraşırken, bunu python döngüsünün temel for döngüsünü kullanarak yapabiliriz. Tek boyutlu bir dizi üzerinde yinelersek, her bir öğeden birer birer geçecektir.

In [55]:
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [57]:
arr = np.array([[1, 2], [4, 5]])

for x in arr:
    for y in x:
        print(y)

1
2
4
5


In [58]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x , "\n")

[[1 2 3]
 [4 5 6]] 

[[ 7  8  9]
 [10 11 12]] 



In [59]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8


* **nditer()** işlevi, çok temelden çok ileri düzey yinelemelere kadar kullanılabilen bir yardımcı işlevdir. Yinelemede karşılaştığımız bazı temel sorunları çözer. 

    for döngülerinde, bir dizinin her skaleri için n adet for döngüsü kullanmamız gerekir ki bu da çok yüksek boyutsallığa sahip diziler için yazmayı zorlaştırır. Fakat nditer() kullanarak bu işlemi basitçe gerçekleştirebiliriz. 

In [60]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


* **op_dtypes** argümanını kullanarak yineleme sırasında öğelerin veri türünü değiştirmek için beklenen veri türünü iletebiliriz.

    NumPy, in-place veri türünü (öğenin dizide olduğu yerde) değiştirmez, bu nedenle bu eylemi gerçekleştirmek için başka bir alana ihtiyaç duyar, bu fazladan boşluğa tampon adı verilir ve onu nditer() içinde etkinleştirmek için flags=['buffered'] parametresini kullanabiliriz.

In [61]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'
